const membersData = {
  "Команда проекта": [
    { name: "berryholls", nickname: "berryholls", roles: 8 },
    { name: "Despectr | Trial Administration", nickname: "despectr", roles: 18 },
    { name: "Source", nickname: "warlordxdd", roles: 3 }
  ],
  "[1000+]🔪": [
    { name: "Bosko Trial French Baguette", nickname: "bosko861", roles: 8 },
    { name: "Despectr | Trial Administration", nickname: "despectr", roles: 18 },
    { name: "Isaac", nickname: "isaacgreene", roles: 6 },
    { name: "lili | Trial Administration", nickname: "lili____", roles: 25 },
    { name: "Olivka", nickname: "olivka6666", roles: 9 }
  ],
  "[100+]🔪": [
    { name: "?CвЯтoЙ¿", nickname: "reaject", roles: 9},
    { name: "Ветер", nickname: "lesnitskiy", roles: 6 },
    { name: "шейх", nickname: "oleg05952", roles: 4 },
    { name: "OZICHokTTV", nickname: "oz1ch", roles: 17 },
    { name: "RusianAkcher", nickname: "rusianachker", roles: 2 },
    { name: "w3ferens", nickname: "w3ferens", roles: 9 }
  ],
  "[500+]🔪": [
    { name: "Тёма Крымский", nickname: "krustalno_poxyu", roles: 11  },
    { name: "Flaer1x", nickname: "02384", roles: 11 },
    { name: "oTeTs", nickname: "die_doteks", roles: 11 },
    { name: "OZICHokTTV(Даня)", nickname: "oz1ch", roles: 17 },
    { name: "佐野万次郎", nickname: "lojkunchi", roles: 24 },
  ],
 "[2500+]🔪": [
    { name: "Майор Гом | Trial Administration", nickname: "sweetbowne", roles: 31 }
  ],
  "Администрация": [
    { name: "Майор Гом | Trial Administration", nickname: "sweetbowne", roles: 31 },
    { name: "Despectr | Trial Administration", nickname: "despectr", roles: 18 },
    { name: "berryholls", nickname: "berryholls", roles: 8 },
    { name: "Хендрик Истерман", nickname: "rrrr6772", roles: 6 },
    { name: "lili | Trial Administration", nickname: "lili____", roles: 25 },
    { name: "Lina of Darkness", nickname: "vasilinalev", roles: 6 },
    { name: "MilissaMckee", nickname: "milissamckee", roles: 27 }
  ],
 "Зам": [
    { name: "berryholls", nickname: "berryholls", roles: 8 }
  ],
 "Главный админ": [
    { name: "Jerry", nickname: "sociopath_jerry", roles: 6 },
    { name: "lili | Trial Administration", nickname: "lili____", roles: 25 },
  ],
  "Грешницы": [
    { name: "! GelyanKalian", nickname: "gelyankalian", roles: 4 },
    { name: "! SANYA_SANTEHNIK", nickname: "corpse_brea2h", roles: 8 },
    { name: "Easterman's 2nd wife", nickname: "redgrave1890", roles: 7 },
    { name: "|🍌|", nickname: "long_yellow_banana", roles: 3 },
    { name: "♡", nickname: "bez_negativa_", roles: 16 },
    { name: "✧ GingerFox", nickname: "gingerfoxyz", roles: 5 },
    { name: "🍓MYSTIC🍓", nickname: "dark_mystic", roles: 7 },
    { name: "🍷kãmîlã", nickname: "fiiolet", roles: 4 },
    { name: "🕷 Sofia 🕸", nickname: "wild.soul.", roles: 2 },
    { name: "ананасовая", nickname: "ananasovayaa1", roles: 3 },
    { name: "Анастасия Т", nickname: "anastasia_t_", roles: 2 },
    { name: "Водичка😈", nickname: "vodichkahuy", roles: 4 },
    { name: "Гаечка", nickname: "gae4ka95", roles: 2 },
    { name: "гомункул", nickname: "gomynkyll", roles: 4 },
    { name: "зилерша/неге олай дейсін бауырым", nickname: "alenkazxdura228", roles: 4 },
    { name: "капитан блант", nickname: "obtortocollo", roles: 4 },
    { name: "Катейка", nickname: "kateykameow", roles: 2 },
    { name: "Кизючка <3", nickname: "kiz.uka", roles: 7 },
    { name: "Лалочка", nickname: "lal04ka", roles: 5 },
    { name: "Майор Гом | Trial Administration", nickname: "sweetbowne", roles: 31 },
    { name: "робо няня", nickname: "sssakura1", roles: 2 },
    { name: "Ada Borsch", nickname: "adaborchtsch", roles: 2 },
    { name: "Albazinka", nickname: "albazinka", roles: 4 },
    { name: "𝔸𝕢𝕦𝕒𝕣𝕚𝕦𝕤", nickname: "kintus11", roles: 3 },
    { name: "AQULA", nickname: "aqula", roles: 2 },
    { name: "asikkks", nickname: "asyandreew", roles: 2 },
    { name: "cattakeme | Ксюша", nickname: "cattakeme", roles: 3 },
    { name: "diaanbaby", nickname: "diaanbaby", roles: 2 },
    { name: "Edna Konrad", nickname: "skylinereed", roles: 8 },
    { name: "Elleksi", nickname: "elleksi", roles: 2 },
    { name: "𝐄𝐌𝐀𝐍-𝐍𝐎𝟓𓃠", nickname: "emanno5", roles: 3 },
    { name: "enfant terrible", nickname: "nimostor", roles: 5 },
    { name: "Evaplatosha", nickname: "evaplatosha", roles: 3 },
    { name: "FOX", nickname: "chilitoxic", roles: 2 },
    { name: "HongKong", nickname: "sunnyhongkong", roles: 10 },
    { name: "ℎ𝑦𝑝𝑜𝑡𝑒𝑛𝑢𝑠𝑒", nickname: "twilightst", roles: 5 },
    { name: "icq", nickname: "meicq", roles: 2 },
    { name: "INSOMNIA", nickname: "lilm1racle", roles: 8 },
    { name: "Ivergence", nickname: "ivergence", roles: 5 },
    { name: "Kaza4ok", nickname: "kaza4ok5393", roles: 5 },
    { name: "Ksenia", nickname: "kseniia20018232", roles: 4 },
    { name: "Lexy", nickname: "lexy_s", roles: 11 },
    { name: "lili | Trial Administration", nickname: "lili____", roles: 25 },
    { name: "Lina of Darkness", nickname: "vasilinalev", roles: 6 },
    { name: "LizaKuz", nickname: "lizakuz", roles: 4 }
  ],
  "Season 5 🥇": [
    { name: "?Святой¿", nickname: "reajeact", roles: 9 },
    { name: "♡", nickname: "bez_negativa_", roles: 16 },
    { name: "Ветер", nickname: "lesnitskiy", roles: 6 },
    { name: "Гарлик Бравлик", nickname: "mr.garlik", roles: 8 },
    { name: "Койл вас в попку", nickname: "xochustudiumvmoskve", roles: 5 },
    { name: "Леон Мем Кеннеди", nickname: "leonkennedy.", roles: 14 },
    { name: "Майор Том | Trial Administration", nickname: "sweetbowne", roles: 31 },
    { name: "Суетолог", nickname: "fedo_ra", roles: 10 },
    { name: "Тёма Крымский", nickname: "krustalno_poxyu", roles: 11 },
    { name: "шейх", nickname: "oleg05952", roles: 4 },
    { name: "blixdsm", nickname: "drslvqx", roles: 3 },
    { name: "Bosko Trial French Baguette", nickname: "bosko861", roles: 8 },
    { name: "Despectr | Trial Administration", nickname: "despectr", roles: 18 },
    { name: "Flaer1x", nickname: "02384", roles: 11 },
    { name: "fuxx", nickname: "ayebassota", roles: 8 },
    { name: "Grief", nickname: "griefgd", roles: 18 },
    { name: "Haxxsmart", nickname: "haxxsmart", roles: 3 },
    { name: "Judge", nickname: "timich0717", roles: 7 },
    { name: "KindaHomeless", nickname: "aguga.ga.ga.ga", roles: 7 },
    { name: "lili | Trial Administration", nickname: "lili____", roles: 25 },
    { name: "MilissaMckee", nickname: "milissamckee", roles: 27 },
    { name: "Olivka", nickname: "olivka6666", roles: 9 },
    { name: "otebites", nickname: "afflictedl", roles: 22 },
    { name: "oTeTs", nickname: "die_doteks", roles: 10 },
    { name: "OZICHokTTV(Даня)", nickname: "oz1ch", roles: 17 },
    { name: "Pardus OO", nickname: "p4rdus", roles: 16 },
    { name: "pollux", nickname: "itspollux", roles: 11 },
    { name: "sh1nell", nickname: "sh1nell", roles: 12 },
    { name: "佐野万次郎", nickname: "lojkunchi", roles: 24 }
],
  "Обратный отсчёт": [
    { name: "Майор Гом | Trial Administration", nickname: "sweetbowne", roles: 31 },
    { name: "Мужские яйца?", nickname: "21_3002", roles: 10 },
    { name: "EugenKontra", nickname: "eugenkontra", roles: 16 },
    { name: "Frokli", nickname: "frokli_", roles: 3 },
    { name: "Lexy", nickname: "lexy_s", roles: 11 },
    { name: "lili | Trial Administration", nickname: "lili____", roles: 25 },
    { name: "MilissaMckee", nickname: "milissamckee", roles: 27 },
    { name: "otebites", nickname: "afflictedl", roles: 22 },
    { name: "Pardus OO", nickname: "p4rdus", roles: 16 },
    { name: "RedBull", nickname: "redbull2436", roles: 11 },
    { name: "Sano", nickname: "justanya.", roles: 11 },
    { name: "Sapienti sat", nickname: "sapientisat.", roles: 23 }
  ],
  "Знаток Пожарной Опасности": [
    { name: ".P.S.I.X.", nickname: "romanbryansk", roles: 11 },
    { name: "Майор Гом | Trial Administration", nickname: "sweetbowne", roles: 31 },
    { name: "ЮРА🕷👁🐑", nickname: "gagarin_tuk", roles: 18 },
    { name: "Despectr | Trial Administration", nickname: "despectr", roles: 18 },
    { name: "Grief", nickname: "griefgd", roles: 18 },
    { name: "Lexy", nickname: "lexy_s", roles: 11 },
    { name: "lili | Trial Administration", nickname: "lili____", roles: 25 },
    { name: "MilissaMckee", nickname: "milissamckee", roles: 27 },
    { name: "otebites", nickname: "afflictedl", roles: 22 },
    { name: "RedBull", nickname: "redbull2436", roles: 11 },
    { name: "Sapienti sat", nickname: "sapientisat.", roles: 22 },
    { name: "佐野万次郎", nickname: "lojkunchi", roles: 24 }
  ],
  "Богомол": [
    { name: "~Gde_Starosta~(?)", nickname: "kostya_peep", roles: 10 },
    { name: "♡", nickname: "bez_negativa_", roles: 16 },
    { name: "Майор Гом | Trial Administration", nickname: "sweetbowne", roles: 31 },
    { name: "Суетолог", nickname: "fedo_ra", roles: 10 },
    { name: "DEATHPROOF", nickname: "deathpr0of", roles: 7 },
    { name: "fuxx", nickname: "ayebassota", roles: 8 },
    { name: "lili | Trial Administration", nickname: "lili____", roles: 25 },
    { name: "MilissaMckee", nickname: "milissamckee", roles: 27 },
    { name: "Novistador", nickname: "werner063745", roles: 0 },
    { name: "otebites", nickname: "afflictedl", roles: 22 },
    { name: "OZICHokTTV(Даня)", nickname: "oz1ch", roles: 17 },
    { name: "Pardus OO", nickname: "p4rdus", roles: 16 },
    { name: "Sapienti sat", nickname: "sapientisat.", roles: 22 },
    { name: "佐野万次郎", nickname: "lojkunchi", roles: 24 }
  ],
   "300. Завет Нового Иезекиля": [
    { name: "♡", nickname: "bez_negativa_", roles: 16 },
    { name: "Майор Гом | Trial Administration", nickname: "sweetbowne", roles: 31 },
    { name: "Despectr | Trial Administration", nickname: "despectr", roles: 18 },
    { name: "Grief", nickname: "griefgd", roles: 18 },
    { name: "Isaac", nickname: "isaacgreene", roles: 6 },
    { name: "lili | Trial Administration", nickname: "lili____", roles: 25 },
    { name: "MilissaMckee", nickname: "milissamckee", roles: 27 },
    { name: "otebites", nickname: "afflictedl", roles: 22 },
    { name: "Pardus OO", nickname: "p4rdus", roles: 16 }
  ],
  "295. Изгнанные в лес": [
    { name: "PY", nickname: "py4090", roles: 7 },
    { name: "佐野万次郎", nickname: "lojkunchi", roles: 24 }
  ],
  "275. Еретик": [
    { name: "꒒ꍏꋪꀤꀘ_꒒ꂦ꒒", nickname: "larik_lol", roles: 12  },
    { name: "Гарлик Бравлик", nickname: "mr.garlik", roles: 8 }
  ],
  "Scavenger": [
    { name: "Майор Гом | Trial Administration", nickname: "sweetbowne", roles: 31, place: 1 },
    { name: "lili | Trial Administration", nickname: "lili____", roles: 25, place: 2 },
    { name: "Sapienti sat", nickname: "sapientisat.", roles: 23, place: 3 },
    { name: "баха", nickname: "igrovoytenko", roles: 4, place: 4 },
    { name: "Pardus OO", nickname: "p4rdus", roles: 16, place: 5 },
    { name: "Richard Trager", nickname: "mekodike", roles: 8 },
    { name: "otebites", nickname: "afflictedl", roles: 22 },
    { name: "Суетолог", nickname: "fedo_ra", roles: 10 },
    { name: "MilissaMckee", nickname: "milissamckee", roles: 27 }
  ],
  "Season 6 🥇": [
    { name: "Pardus OO", nickname: "p4rdus", roles: 16, place: 1 },
    { name: "lili | Trial Administration", nickname: "lili____", roles: 25, place: 2 },
    { name: "Майор Гом | Trial Administration", nickname: "sweetbowne", roles: 31, place: 3 },
    { name: "sh1nell", nickname: "sh1nell", roles: 12, place: 4  },
    { name: "~Gde_Starosta~(?)", nickname: "kostya_peep", roles: 10, place: 5 },
    { name: "otebites", nickname: "afflictedl", roles: 22 }
   ],
  "Легенда": [
  { name: "! 𝐚𝐝𝐚𝐦_𝐜𝐨𝐧𝐨𝐫", nickname: "conoroff", roles: 4 },
  { name: "☭", nickname: "itz_miny", roles: 3 },
  { name: "꒒ꍏꋪꀤꀘ_꒒ꂦ꒒", nickname: "larik_lol", roles: 12 },
  { name: "$ectarian", nickname: "secta148", roles: 13 },
  { name: "11asK", nickname: "deq91", roles: 3 },
  { name: "Булочка", nickname: "buka_899", roles: 5 },
  { name: "вотфо шнеле шнеле", nickname: "govno059", roles: 5 },
  { name: "Кирбитик", nickname: "vladke3rby", roles: 4 },
  { name: "Леон Мем Кеннеди", nickname: "leonkennedy.", roles: 14 },
  { name: "Майор Гом | Trial Administration", nickname: "sweetbowne", roles: 31 },
  { name: "Максим", nickname: "synyi", roles: 3 },
  { name: "отец?", nickname: "takioma.", roles: 5 },
  { name: "Печенег", nickname: "forchyn", roles: 4 },
  { name: "розетка", nickname: "rozirka", roles: 9 },
  { name: "Сын Сурса", nickname: "drunknasty_", roles: 4 },
  { name: "талантливая мышь", nickname: "yhnmbqjkl", roles: 3 },
  { name: "Харви", nickname: "kharvi0818", roles: 14 },
  { name: "Banzai", nickname: "banzai2773", roles: 10 },
  { name: "Bonnati", nickname: "bonnati", roles: 4 },
  { name: "Creeposseen", nickname: "creeposseen", roles: 3 },
  { name: "D i s a n 1 r", nickname: "pupsik41818", roles: 4 },
  { name: "D3R", nickname: "dmitriymeto", roles: 25 },
  { name: "DeadbyPing", nickname: "ping_not_die", roles: 5 },
  { name: "DeeVore [Даша]", nickname: "kosandra9", roles: 2 },
  { name: "Deluxeagle", nickname: "ruzgtyvink", roles: 4 },
  { name: "Despectr | Trial Administration", nickname: "despectr", roles: 18 },
  { name: "DrPenisoida", nickname: "mixks228", roles: 4 },
  { name: "Edna Konrad", nickname: "skylinereed", roles: 8 },
  { name: "Evaplatosha", nickname: "evaplatosha", roles: 3 },
  { name: "Grief", nickname: "griefgd", roles: 18 },
  { name: "Hir", nickname: "vika_nika__26852", roles: 3 },
  { name: "IVAN", nickname: "niger3879", roles: 6 },
  { name: "jim", nickname: "keq_", roles: 4 },
  { name: "𝓚𝓪𝓻𝓪_𝓓𝓐𝓝", nickname: "kara_dan", roles: 6 },
  { name: "Kokos1k", nickname: "kokos1k_x", roles: 3 },
  { name: "ksenyX", nickname: "vorobusek", roles: 2 },
  { name: "lili | Trial Administration", nickname: "lili____", roles: 25 },
  { name: "Lina of Darkness", nickname: "vasilinalev", roles: 6 },
  { name: "lukovka", nickname: "lukovkamary", roles: 4 },
  { name: "mamyko", nickname: ".mamyko", roles: 6 },
  { name: "MilissaMckee", nickname: "milissamckee", roles: 27 },
  { name: "OZICHokTTV(Даня)", nickname: "oz1ch", roles: 17 },
  { name: "pollux", nickname: "itspollux", roles: 12 },
  { name: "remu", nickname: "remuls", roles: 5 },
  { name: "Richard Trager", nickname: "mekodike", roles: 8 },
  { name: "rYOGURT [Дана]", nickname: "d1stort1on93", roles: 6 },
  { name: "simkins", nickname: "simkinsi", roles: 6 },
  { name: "Sosiske", nickname: "pelmeni764", roles: 5 },
  { name: "Spartak_CSKA", nickname: "spartak0456", roles: 4 },
  { name: "tosprov", nickname: "tosprov", roles: 6 },
  { name: "Vladoser", nickname: "mrvladoser", roles: 7 },
  { name: "佐野万次郎", nickname: "lojkunchi", roles: 24 }
],
  "Ностофоб": [
    { name: ".P.S.I.X.", nickname: "romanbryansk", roles: 11 },
    { name: "꒒ꍏꋪꀤꀘ_꒒ꂦ꒒", nickname: "larik_lol", roles: 12  },
    { name: "Майор Гом | Trial Administration", nickname: "sweetbowne", roles: 31 },
    { name: "Prezent", nickname: "prezentt", roles: 5 },
    { name: "Sano", nickname: "justanya.", roles: 11 },
    { name: "Sapienti sat", nickname: "sapientisat.", roles: 23 },
    { name: "佐野万次郎", nickname: "lojkunchi", roles: 24 }
   ],  
  "Prime Time": [
    { name: "Майор Гом | Trial Administration", nickname: "sweetbowne", roles: 31 },
    { name: "Sapienti sat", nickname: "sapientisat.", roles: 23 },
    { name: "佐野万次郎", nickname: "lojkunchi", roles: 24 }
   ],
  "Бамбино": [
    { name: "|𝐌𝐨𝐨𝐧|", nickname: ".moon_1x", roles: 11 },
    { name: "$ectarian", nickname: "secta148", roles: 13 },
    { name: "Мужские яйца?", nickname: "21_3002", roles: 10 },
    { name: "Prezent", nickname: "prezentt", roles: 5 },
    { name: "розетка", nickname: "rozirka", roles: 9 },
    { name: "Sapienti sat", nickname: "sapientisat.", roles: 23 },
    { name: "distaves", nickname: "distaves", roles: 13 }
   ],
  "Егерь": [
    { name: "|𝐌𝐨𝐨𝐧|", nickname: ".moon_1x", roles: 11 },
    { name: "Леон Мем Кеннеди", nickname: "leonkennedy.", roles: 14 },
    { name: "Печенег", nickname: "forchyn", roles: 4 },
    { name: "A...", nickname: "agamariff", roles: 2 },
    { name: "FYQR Лягушка", nickname: "trap.8016", roles: 9 },
    { name: "lili | Trial Administration", nickname: "lili____", roles: 25 },
    { name: "MilissaMckee", nickname: "milissamckee", roles: 27 },
    { name: "otebites", nickname: "afflictedl", roles: 22 },
    { name: "rYOGURT [Дана]", nickname: "d1stort1on93", roles: 6 },
    { name: "Sano", nickname: "justanya.", roles: 11 },
    { name: "Sapienti sat", nickname: "sapientisat.", roles: 23 }
   ],
  "Кресс": [
    { name: "꒒ꍏꋪꀤꀘ_꒒ꂦ꒒", nickname: "larik_lol", roles: 12  },
    { name: "Майор Гом | Trial Administration", nickname: "sweetbowne", roles: 31 },
    { name: "I need it", nickname: "xronxad", roles: 7 },
    { name: "Sano", nickname: "justanya.", roles: 11 },
    { name: "Sapienti sat", nickname: "sapientisat.", roles: 23 },
    { name: "tosprov", nickname: "tosprov", roles: 6 },
    { name: "佐野万次郎", nickname: "lojkunchi", roles: 24 }
   ],
  "Geister": [
    { name: ".P.S.I.X.", nickname: "romanbryansk", roles: 11 },
    { name: "♡", nickname: "bez_negativa_", roles: 16 },
    { name: "Ватафакер Мазафакер", nickname: "gloomyl", roles: 4 },
    { name: "Двухсотый", nickname: "dvuhsotiy200_", roles: 5 },
    { name: "Кизючка <3", nickname: "kiz.uka", roles: 7 },
    { name: "Леон Мем Кеннеди", nickname: "leonkennedy.", roles: 14 },
    { name: "Майор Гом | Trial Administration", nickname: "sweetbowne", roles: 31 },
    { name: "Овсяная Каша", nickname: "_morgenshtern_", roles: 7 },
    { name: "тихий_омут", nickname: "tiasmaz", roles: 3 },
    { name: "Хрюша Сковородкин", nickname: "teashark11", roles: 4 },
    { name: "ЮРА🕷👁🐑", nickname: "gagarin_tuk", roles: 18 },
    { name: "Despectr | Trial Administration", nickname: "despectr", roles: 18 },
    { name: "Dess", nickname: "deared232", roles: 7 },
    { name: "distaves", nickname: "distaves", roles: 13 },
    { name: "Dunstent", nickname: "dunstent", roles: 3 },
    { name: "EugenKontra", nickname: "eugenkontra", roles: 16 },
    { name: "fuxx", nickname: "ayebassota", roles: 8 },
    { name: "Gaspar", nickname: "mr.gaspar", roles: 2 },
    { name: "Grief", nickname: "griefgd", roles: 18 },
    { name: "I need it", nickname: "xronxad", roles: 7 },
    { name: "Lexy", nickname: "lexy_s", roles: 11 },
    { name: "lili | Trial Administration", nickname: "lili____", roles: 25 },
    { name: "Matrix?/", nickname: "mark44636", roles: 5 },
    { name: "MilissaMckee", nickname: "milissamckee", roles: 27 },
    { name: "otebites", nickname: "afflictedl", roles: 22 },
    { name: "Pliush_ka", nickname: "pliush_ka", roles: 3 },
    { name: "RedBull", nickname: "redbull2436", roles: 11 },
    { name: "Sapienti sat", nickname: "sapientisat.", roles: 23 },
    { name: "Ysach Borodach", nickname: "ysach_borodach", roles: 4 },
    { name: "佐野万次郎", nickname: "lojkunchi", roles: 24 }
   ],
  "Winter Kills": [
    { name: ".P.S.I.X.", nickname: "romanbryansk", roles: 11 },
    { name: "|𝐌𝐨𝐨𝐧|", nickname: ".moon_1x", roles: 11 },
    { name: "♡", nickname: "bez_negativa_", roles: 16 },
    { name: "баха", nickname: "igrovoytenko", roles: 4  },
    { name: "илюшк", nickname: "apostol.ilushk", roles: 7 },
    { name: "Кизючка <3", nickname: "kiz.uka", roles: 7 },
    { name: "Кошечка Mitake", nickname: "karmamitake", roles: 8 },
    { name: "Леон Мем Кеннеди", nickname: "leonkennedy.", roles: 14 },
    { name: "Майор Гом | Trial Administration", nickname: "sweetbowne", roles: 31 },
    { name: "самец", nickname: "fog13i", roles: 11 },
    { name: "сифæ тауæгхуй", nickname: "darkknight0054", roles: 3 },
    { name: "Харви", nickname: "kharvi0818", roles: 14 },
    { name: "ЮРА🕷👁🐑", nickname: "gagarin_tuk", roles: 18 },
    { name: "Despectr | Trial Administration", nickname: "despectr", roles: 18 },
    { name: "Dess", nickname: "deared232", roles: 7 },
    { name: "distaves", nickname: "distaves", roles: 13 },
    { name: "Flaer1x", nickname: "02384", roles: 11 },
    { name: "fuxx", nickname: "ayebassota", roles: 8 },
    { name: "Grief", nickname: "griefgd", roles: 18 },
    { name: "INSOMNIA", nickname: "lilm1racle", roles: 8 },
    { name: "lili | Trial Administration", nickname: "lili____", roles: 25 },
    { name: "Matrix?/", nickname: "mark44636", roles: 5 },
    { name: "MilissaMckee", nickname: "milissamckee", roles: 27 },
    { name: "Nightly", nickname: "xnightly113", roles: 4 },
    { name: "otebites", nickname: "afflictedl", roles: 22 },
    { name: "OZICHokTTV(Даня)", nickname: "oz1ch", roles: 17 },
    { name: "Pardus OO", nickname: "p4rdus", roles: 16 },
    { name: "parenec", nickname: "parenec", roles: 10 },
    { name: "RuZZn", nickname: "ruzzn", roles: 11 },
    { name: "rYOGURT [Дана]", nickname: "d1stort1on93", roles: 6 },
    { name: "Sano", nickname: "justanya.", roles: 11 },
    { name: "Sapienti sat", nickname: "sapientisat.", roles: 23 },
    { name: "Seeming", nickname: "seeming", roles: 6 },
    { name: "Sparron", nickname: "milokiu", roles: 2 },
    { name: "SSSmokin", nickname: "sss1nner", roles: 4 },
    { name: "timlOS", nickname: "timlos", roles: 2 },
    { name: "Valensia", nickname: "valensia_oxana", roles: 12 },
    { name: "W1nche$t3r", nickname: "w1nchesst3r", roles: 4 },
    { name: "w3ferens", nickname: "w3ferens", roles: 9 },
    { name: "佐野万次郎", nickname: "lojkunchi", roles: 24 }
   ],
  "Коллекционер": [
    { name: "~Gde_Starosta~(?)", nickname: "kostya_peep", roles: 10 },
    { name: "crøssfade 𒉭", nickname: ".interactive.", roles: 11 },
    { name: "kendzni.", nickname: "kendzni.", roles: 6 },
    { name: "Pardus OO", nickname: "p4rdus", roles: 16 },
    { name: "Suraluve", nickname: "suraluve", roles: 14 },
   ],
  "40. Мне не нужен свет": [
    { name: "!/Light", nickname: "sexiguy123" },
    { name: "?", nickname: "zip7071" },
    { name: "#", nickname: "kkiiltysae" },
    { name: "÷untake÷-?", nickname: "h1lans" },
    { name: "\\ \\✧ Sad✧//", nickname: "sadmiral77" },
    { name: "︶꒦꒷íQ GojoメSAT0RUジ", nickname: "alksey" },
    { name: "♫:🎧☆Sattin♫:🎧✩", nickname: "katrinjesso" },
    { name: "44", nickname: "grxveyxrd" },
    { name: "Анжела Рыгало", nickname: "gospozha_kuraga" },
    { name: "Álexes", nickname: "alex_es" },
    { name: "Боня", nickname: "cultwaye" },
    { name: "Василий Валерьевич", nickname: "limex6666" },
    { name: "Доза", nickname: "dozamaika20" },
    { name: "злодей британец", nickname: "thekidfomin" },
    { name: "котик с автоматом", nickname: "chartik_duckbill" },
    { name: "Меланхоличная лярва", nickname: "crownpsh" },
    { name: "Молочко Айран", nickname: "molochko_ayran" },
    { name: "мразота", nickname: ".davlix" },
    { name: "нимфоманка", nickname: "yungw4ng" },
    { name: "пися какапися", nickname: "china9672" },
    { name: "раст", nickname: "worldisfucked" },
    { name: "Сквидвард-аба", nickname: "fedora_sieli_gopniki" },
    { name: "Служанка капитана moge-kov'a", nickname: "prosto_ratchet" },
    { name: "СЫН СООБЩЕСТВО", nickname: "power_point4" },
    { name: "Тёма", nickname: "fire_galaxyy" },
    { name: "Тёма ПГСник", nickname: ".artemiy_" },
    { name: "Toгo", nickname: "almaz887" },
    { name: "жк-кф¿", nickname: "milesupshur__74559" },
    { name: "AliAlehandro85", nickname: "alialehandro85" },
    { name: "Artist, uh SD", nickname: "chaz3720" },
    { name: "azart", nickname: "sex0qw" },
    { name: "Bahomet(Сергей)", nickname: "smail_666_satanist" },
    { name: "Baka Maka", nickname: "bakamaka2" },
    { name: "bleed grey", nickname: "lashkattt" },
    { name: "bobi", nickname: "bobikkxd" },
    { name: "¢հąøʂ✧", nickname: "chaosqq" },
    { name: "cheese", nickname: "cheese789" },
    { name: "Chizer", nickname: "chizeroff" },
    { name: "Chuuuuuka", nickname: "chuuuuuka" },
    { name: "D3R", nickname: "dmitriymeto" },
    { name: "Dacota Blagger", nickname: "dacota.blagger" },
    { name: "eeee skn", nickname: "eeeeskn" },
    { name: "extaZZZ", nickname: "extazzz8022" },
    { name: "f/y/m", nickname: "sykablya228" },
    { name: "Ferverk", nickname: "ferverk_op" },
    { name: "Fran", nickname: "fran.ed1ts" },
    { name: "god damn", nickname: "getdonked69" },
    { name: "Hisada", nickname: "hisadaa" },
    { name: "HomerSunn", nickname: "homersunn" },
    { name: "Ƨєяαя", nickname: "stolasio" },
    { name: "jim", nickname: "keq_" },
    { name: "Kayoshi", nickname: "kayoshiaf" },
    { name: "KenniMak", nickname: "meguminmesha" },
    { name: "KORNEPLOD", nickname: "korneplodina" },
    { name: "Kreinik", nickname: "kreinik" },
    { name: "KROSHILOV", nickname: "kroshilove" },
    { name: "Kutep", nickname: "kutep1" },
    { name: "kvokka", nickname: "kvokka007" },
    { name: "kwwiiziee", nickname: "kwwiiziee" },
    { name: "кузя", nickname: "nikitosik2281889" },
    { name: "maska67_sa", nickname: "maska67_sa" },
    { name: "MeerCat", nickname: "meercat1" },
    { name: "Minos Dripe", nickname: "zxcbeliever" },
    { name: "mld8nk", nickname: "taniastv" },
    { name: "muhadzhan", nickname: "tr_ambassador808" },
    { name: "Nihon Go", nickname: "nihongo123" },
    { name: "nik", nickname: "ghost3215" },
    { name: "pengrad1", nickname: "pengrad1" },
    { name: "Pesileus(Ilya)", nickname: "huskydog949" },
    { name: "Pipusik", nickname: "pipusik67" },
    { name: "Piter Grifin", nickname: "liptun34172" },
    { name: "Pliush_ka", nickname: "pliush_ka" },
    { name: "Raulf", nickname: "astral201001" },
    { name: "REZZnik", nickname: "rezznik_" },
    { name: "SAMURAI", nickname: "samurai_9745" },
    { name: "Sard_32", nickname: "sard_32" },
    { name: "seanchai", nickname: "seanechai" },
    { name: "So horny", nickname: "nimfarize" },
    { name: "Soco", nickname: "belka05598" },
    { name: "Spele_Part", nickname: "spele_part" },
    { name: "spliffinme", nickname: "fxiks" },
    { name: "Sywerk", nickname: "sywerk" },
    { name: "Turbo", nickname: "turbo0_9" },
    { name: "weanehh✿", nickname: "weanehh" },
    { name: "winterwntend 𓆩 ♡ 𓆪", nickname: "winterwntend" },
    { name: "wnskx", nickname: "jdhuabd" },
    { name: "Xxx", nickname: "pokhui1263" },
    { name: "YOUNG ICE", nickname: "youngice4389" },
    { name: "ZLOBA", nickname: "zlozloba" },
    { name: "死Lamia死", nickname: "shisotired" },
  ],
   "50. Под наблюдением": [
    { name: "! virtyøz", nickname: "misfistik" },
    { name: "◻◼◻◼◻ GΛN ◻◼◻◼◻", nickname: "gan0107" },
    { name: "||||||||||||", nickname: "thetraktorblyat" },
    { name: "алкогомик", nickname: "kroki_dile" },
    { name: "владимир томатов", nickname: "craizi4444" },
    { name: "завер", nickname: "zawer8840" },
    { name: "играю баху", nickname: "igrovoytenko" },
    { name: "кактус", nickname: "rubabuba_original" },
    { name: "Кеморе", nickname: "smokeart888" },
    { name: "Миф", nickname: "myfatra" },
    { name: "Ночная Стерва", nickname: "offstrate" },
    { name: "отец?", nickname: "takioma." },
    { name: "Руди", nickname: "trollman0306" },
    { name: "Смоленцев", nickname: "ncolosso" },
    { name: "француз", nickname: "francuz7474" },
    { name: "ЧифирОчек", nickname: "thievlol" },
    { name: "я утка2", nickname: "okmadar345" },
    { name: "alkkoo", nickname: "alkkoo" },
    { name: "Androw Winchester", nickname: "androwwinchester" },
    { name: "avokado", nickname: "avokcado" },
    { name: "ay", nickname: "y.33h" },
    { name: "Barbarjuk", nickname: "sashka0000" },
    { name: "Basy", nickname: "basy_im" },
    { name: "bhinu", nickname: "bhiny" },
    { name: "bibika", nickname: "cy6ersex" },
    { name: "C_r-A--z_Y", nickname: "mark25624" },
    { name: "Charlie Kirk", nickname: "usec2071" },
    { name: "Connor", nickname: "kolijva" },
    { name: "CramFlame", nickname: "cramflame481" },
    { name: "CreatorC", nickname: "emilianokb" },
    { name: "D$NchIK", nickname: "denchik1144" },
    { name: "Denji", nickname: "denji2157" },
    { name: "ƒuga", nickname: "fuga6373" },
    { name: "Grøf", nickname: "bladflag" },
    { name: "Guy.", nickname: "guttibai" },
    { name: "Huffer", nickname: "huffer0206" },
    { name: "James", nickname: "jamesking05" },
    { name: "kelman", nickname: "kelman9706" },
    { name: "Kim", nickname: "ati_kkallu" },
    { name: "Kirito_Kirigaya", nickname: "kirito_61" },
    { name: "korabl", nickname: "hitmehardxd" },
    { name: "Litern", nickname: "l1tern" },
    { name: "LP", nickname: "princes1to" },
    { name: "Mango", nickname: "vvveless" },
    { name: "moa", nickname: "i3y6" },
    { name: "n1kaslss", nickname: "n1kaslss" },
    { name: "ННЕЙ", nickname: "nheu." },
    { name: "Pipirka", nickname: "pipirka_." },
    { name: "Reik!", nickname: "reik2009" },
    { name: "RekRut×Rash×Yepta", nickname: "rekrutrashyepta" },
    { name: "RénDest", nickname: "rendest" },
    { name: "SeefVirst", nickname: "seefvirst" },
    { name: "SolEk82701", nickname: "solek82701" },
    { name: "sshisst", nickname: "darkskull2023" },
    { name: "tenzo", nickname: "anaphb3t" },
    { name: "Tepachok", nickname: "tepachok" },
    { name: "tere .thegarden", nickname: "tere.thegarden" },
    { name: "TerribleDinosaur", nickname: "terribledinosaur" },
    { name: "Twiiinkiii_(den)", nickname: "twiiinkiii" },
    { name: "Valensia", nickname: "valensia_oxana" },
    { name: "varg", nickname: "wrhees" },
    { name: "vpechatlyaet", nickname: "iwatchyourstream" },
    { name: "yuioppoiuy", nickname: "yuioppoiyu" },
    { name: "Zetrix", nickname: "8e8raluv" }
  ]
};

