const membersData = {
  "Команда проекта": [
    { name: "berryholls", nickname: "berryholls", roles: 7 },
    { name: "Despectr | Trial Administration", nickname: "despectr", roles: 18 },
    { name: "CL Support", nickname: "miuuu0905", roles: 2 },
    { name: "✭", nickname: "cult_of_nightmare", roles: 13 },
    { name: "Source", nickname: "warlordxdd", roles: 3 }
  ],
  "[1000+]🔪": [
    { name: "Bosko Trial French Baguette", nickname: "bosko861", roles: 8 },
    { name: "Despectr | Trial Administration", nickname: "despectr", roles: 18 },
    { name: "Divine", nickname: "_divine9_", roles: 12 },
    { name: "Isaac", nickname: "isaacgreene", roles: 6 },
    { name: "lili | Trial Administration", nickname: "lili____", roles: 22 },
    { name: "Olivka", nickname: "olivka6666", roles: 9 }
  ],
  "[100+]🔪": [
    { name: "?CвЯтoЙ¿", nickname: "reaject", roles: 9},
    { name: "Ветер", nickname: "lesnitskiy", roles: 6 },
    { name: "шейх", nickname: "oleg05952", roles: 4 },
    { name: "OZICHokTTV", nickname: "oz1ch", roles: 17 },
    { name: "RusianAkcher", nickname: "rusianachker", roles: 2 },
    { name: "w3ferens", nickname: "w3ferens", roles: 9 }
  ],
  "[500+]🔪": [
    { name: "Тёма Крымский", nickname: "krustalno_poxyu", roles: 11  },
    { name: "Flaer1x", nickname: "02384", roles: 11 },
    { name: "oTeTs", nickname: "die_doteks", roles: 11 },
    { name: "OZICHokTTV", nickname: "oz1ch", roles: 17 },
    { name: "佐野万次郎", nickname: "lojkunchi", roles: 24 },
  ],
 "[2500+]🔪": [
    { name: "✭", nickname: "cult_of_nightmare", roles: 13  },
    { name: "Майор Гом | Trial Administration", nickname: "sweetbowne", roles: 29 },
    { name: "HelenKever", nickname: "helenkever", roles: 15 },
  ],
  "Администрация": [
    { name: "Майор Гом | Trial Administration", nickname: "sweetbowne", roles: 29 },
    { name: "Despectr | Trial Administration", nickname: "despectr", roles: 18 },
    { name: "berryholls", nickname: "berryholls", roles: 7 },
    { name: "Хендрик Истерман", nickname: "rrrr6772", roles: 6 },
    { name: "lili | Trial Administration", nickname: "lili____", roles: 22 },
    { name: "Lina of Darkness", nickname: "vasilinalev", roles: 6 },
    { name: "MilissaMckee", nickname: "milissamckee", roles: 26 }
  ],
 "Зам": [
    { name: "✭", nickname: "cult_of_nightmare", roles: 13 }
  ],
 "Главный админ": [
    { name: "Jerry", nickname: "sociopath_jerry", roles: 6 }
  ],
  "Грешницы": [
    { name: "! GelyanKalian", nickname: "gelyankalian", roles: 4 },
    { name: "! SANYA_SANTEHNIK", nickname: "corpse_brea2h", roles: 8 },
    { name: "Easterman's 2nd wife", nickname: "redgrave1890", roles: 7 },
    { name: "|🍌|", nickname: "long_yellow_banana", roles: 3 },
    { name: "♡", nickname: "bez_negativa_", roles: 16 },
    { name: "✧ GingerFox", nickname: "gingerfoxyz", roles: 5 },
    { name: "🍓MYSTIC🍓", nickname: "dark_mystic", roles: 7 },
    { name: "🍷kãmîlã", nickname: "fiiolet", roles: 4 },
    { name: "🕷 Sofia 🕸", nickname: "wild.soul.", roles: 2 },
    { name: "ананасовая", nickname: "ananasovayaa1", roles: 3 },
    { name: "Анастасия Т", nickname: "anastasia_t_", roles: 2 },
    { name: "Водичка😈", nickname: "vodichkahuy", roles: 4 },
    { name: "Гаечка", nickname: "gae4ka95", roles: 2 },
    { name: "гомункул", nickname: "gomynkyll", roles: 4 },
    { name: "зилерша/неге олай дейсін бауырым", nickname: "alenkazxdura228", roles: 4 },
    { name: "капитан блант", nickname: "obtortocollo", roles: 4 },
    { name: "Катейка", nickname: "kateykameow", roles: 2 },
    { name: "Кизючка <3", nickname: "kiz.uka", roles: 7 },
    { name: "Лалочка", nickname: "lal04ka", roles: 5 },
    { name: "Майор Гом | Trial Administration", nickname: "sweetbowne", roles: 29 },
    { name: "робо няня", nickname: "sssakura1", roles: 2 },
    { name: "Ada Borsch", nickname: "adaborchtsch", roles: 2 },
    { name: "Albazinka", nickname: "albazinka", roles: 4 },
    { name: "𝔸𝕢𝕦𝕒𝕣𝕚𝕦𝕤", nickname: "kintus11", roles: 3 },
    { name: "AQULA", nickname: "aqula", roles: 2 },
    { name: "asikkks", nickname: "asyandreew", roles: 2 },
    { name: "cattakeme | Ксюша", nickname: "cattakeme", roles: 3 },
    { name: "diaanbaby", nickname: "diaanbaby", roles: 2 },
    { name: "Edna Konrad", nickname: "skylinereed", roles: 8 },
    { name: "Elleksi", nickname: "elleksi", roles: 2 },
    { name: "𝐄𝐌𝐀𝐍-𝐍𝐎𝟓𓃠", nickname: "emanno5", roles: 3 },
    { name: "enfant terrible", nickname: "nimostor", roles: 5 },
    { name: "Evaplatosha", nickname: "evaplatosha", roles: 3 },
    { name: "FOX", nickname: "chilitoxic", roles: 2 },
    { name: "HelenKever", nickname: "helenkever", roles: 15 },
    { name: "HongKong", nickname: "sunnyhongkong", roles: 10 },
    { name: "ℎ𝑦𝑝𝑜𝑡𝑒𝑛𝑢𝑠𝑒", nickname: "twilightst", roles: 5 },
    { name: "icq", nickname: "meicq", roles: 2 },
    { name: "INSOMNIA", nickname: "lilm1racle", roles: 8 },
    { name: "Ivergence", nickname: "ivergence", roles: 5 },
    { name: "Kaza4ok", nickname: "kaza4ok5393", roles: 5 },
    { name: "Ksenia", nickname: "kseniia20018232", roles: 4 },
    { name: "Lexy", nickname: "lexy_s", roles: 11 },
    { name: "lili | Trial Administration", nickname: "lili____", roles: 22 },
    { name: "Lina of Darkness", nickname: "vasilinalev", roles: 6 },
    { name: "LizaKuz", nickname: "lizakuz", roles: 4 },
  ],
   };
